/* Copyright (c) 2024-present Venky Corp. */

import type { DataSource } from '@/lib/core/common/ds/types/DataSource';
import { DefaultAttribute, DefaultDataSource, DefaultFullAccess, DefaultReadOnlyAccess } from '../defaults';
import type { Audit } from '@/lib/common/ds/types/core/Audit';
import { getPrefix } from '@/lib/server/constants';
const PREFIX = getPrefix();

export const AuditDataSource: DataSource<Audit> = {
  ...DefaultDataSource,
  id: 'Audit',
  tableName: `${PREFIX}audit`,
  attributes: [
    {
      ...DefaultAttribute,
      code: 'attributeCode',
      name: 'Attribute Code',
      type: 'Text',
      column: 'attribute_code',
      maxLength: 40,
      optional: false,
    },
    {
      ...DefaultAttribute,
      code: 'auditId',
      name: 'Audit Id',
      type: 'Number',
      column: 'audit_id',
      primary: true,
      auto: true,
      optional: false,
    },
    {
      ...DefaultAttribute,
      code: 'datasourceId',
      name: 'Datasource Id',
      type: 'Text',
      column: 'datasource_id',
      maxLength: 40,
      optional: false,
    },
    {
      ...DefaultAttribute,
      code: 'newClobValue',
      name: 'New Clob Value',
      type: 'Text',
      column: 'new_clob_value',
      maxLength: 99999,
    },
    {
      ...DefaultAttribute,
      code: 'newDatetimeValue',
      name: 'New Datetime Value',
      type: 'Date',
      column: 'new_datetime_value',
    },
    {
      ...DefaultAttribute,
      code: 'newDoubleValue',
      name: 'New Double Value',
      type: 'Number',
      column: 'new_double_value',
      allowDecimals: true,
    },
    {
      ...DefaultAttribute,
      code: 'newStringValue',
      name: 'New String Value',
      type: 'Text',
      column: 'new_string_value',
      maxLength: 512,
    },
    {
      ...DefaultAttribute,
      code: 'oldClobValue',
      name: 'Old Clob Value',
      type: 'Text',
      column: 'old_clob_value',
      maxLength: 99999,
    },
    {
      ...DefaultAttribute,
      code: 'oldDatetimeValue',
      name: 'Old Datetime Value',
      type: 'Date',
      column: 'old_datetime_value',
    },
    {
      ...DefaultAttribute,
      code: 'oldDoubleValue',
      name: 'Old Double Value',
      type: 'Number',
      column: 'old_double_value',
      allowDecimals: true,
    },
    {
      ...DefaultAttribute,
      code: 'oldStringValue',
      name: 'Old String Value',
      type: 'Text',
      column: 'old_string_value',
      maxLength: 512,
    },
    {
      ...DefaultAttribute,
      code: 'pkValue',
      name: 'Pk Value',
      type: 'Text',
      column: 'pk_value',
      maxLength: 120,
      optional: false,
    },
    {
      ...DefaultAttribute,
      code: 'updatedAt',
      name: 'Updated At',
      type: 'Date',
      column: 'updated_at',
      optional: false,
    },
    {
      ...DefaultAttribute,
      code: 'updatedBy',
      name: 'Updated By',
      type: 'Text',
      column: 'updated_by',
      maxLength: 128,
      optional: false,
    },
    {
      ...DefaultAttribute,
      code: 'valueType',
      name: 'Value Type',
      type: 'Text',
      column: 'value_type',
      maxLength: 20,
      optional: false,
    },
    {
      ...DefaultAttribute,
      code: 'appId',
      name: 'App Id',
      type: 'Text',
      column: 'app_id',
      maxLength: 128,
      optional: false,
      defaultValue: 'APP_ID',
    },
  ],
  access: [
    {
      ...DefaultReadOnlyAccess,
      insert: true,
      roleCode: 'all_users',
    },
    {
      ...DefaultFullAccess,
      roleCode: 'admin',
    },
  ],
};
