// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DateFilter =
  | { on: string }
  | { noton: string }
  | { empty: string }
  | { notempty: string }
  | { after: string }
  | { before: string }
  | { beforetime: string }
  | { onorafter: string }
  | { onorbefore: string }
  | { today: string }
  | { yesterday: string }
  | { tomorrow: string }
  | { last7days: string }
  | { last14days: string }
  | { last28days: string }
  | { next7days: string }
  | { next14days: string }
  | { next28days: string }
  | { thisweek: string }
  | { thismonth: string }
  | { thisquarter: string }
  | { thisyear: string }
  | { inthepast: string }
  | { inthefuture: string };
