// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalDatasource = {
  externalDsId: string;
  authApi?: string;
  describeApi?: string;
  queryApi?: string;
  postApi?: string;
};
