// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MultiStringFilter =
  | { hasall: Array<string>; ignoreCase?: boolean }
  | { hasany: Array<string>; ignoreCase?: boolean }
  | { notany: Array<string>; ignoreCase?: boolean }
  | { in: Array<string>; ignoreCase?: boolean }
  | { nin: Array<string>; ignoreCase?: boolean };
