// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NumberFilter =
  | { eq: number }
  | { is: number }
  | { ne: number }
  | { not: number }
  | { gt: number }
  | { gte: number }
  | { lt: number }
  | { lte: number }
  | { null: number }
  | { notnull: number };
