// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StringFilter =
  | { is: string; ignoreCase?: boolean }
  | { not: string; ignoreCase?: boolean }
  | { empty: string }
  | { notempty: string }
  | { nct: string; ignoreCase?: boolean }
  | { like: string; ignoreCase?: boolean }
  | { sw: string; ignoreCase?: boolean }
  | { ew: string; ignoreCase?: boolean }
  | { slt: string }
  | { sgt: string };
