// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UUIDFilter =
  | { is: string }
  | { not: string }
  | { empty: string }
  | { notempty: string }
  | { isafter: string }
  | { isbefore: string };
