// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type YNFilter = { is: string } | { empty: string } | { notempty: string };

export type TFFilter = YNFilter;
